### ISSUE TITLE
[New Cohort] Introduction to Mathematical Thinking

### ISSUE THREAD

**Issue by Nixerrr** [ossu/cohorts#10]
## Class

[Computer Science / Extra Math / Introduction to Mathematical Thinking](https://www.coursera.org/learn/mathematical-thinking)

## Coordinators (1/3)

- [Nikos Panaiotu](https://github.com/Nixerrr)

## Students (3/20)

- [Nikos Panaiotu](https://github.com/Nixerrr)
- [Vivek Poddar](https://github.com/vivekimsit)
- [Mikhail Kirillov](https://github.com/w96k)

## Start Date

February 5, 2018

**Comment by Nixerrr** [comment]
DISCLAIMER: This course is no longer part of the main curriculum but has been relegated to the extras.

**Comment by vivekimsit** [comment]
Vivek Poddar

**Comment by w96k** [comment]
I'm in (:

**Comment by Nixerrr** [comment]
Great! What platform would you guys like to use for communication? Gitter? Slack? Or something different?

**Comment by vivekimsit** [comment]
I would like to stick to slack that we are already using

**Comment by Nixerrr** [comment]
OK, let's do that. I've created a channel called #math-thinking. 

Mikhail, here is an invitation for the OSSU Slack channel, if you're not on it yet, join and find the #math-thinking channel: [OSSU Slack workspace](https://join.slack.com/t/ossuniversity/shared_invite/enQtMjk4NDA5NDAzMzkyLTkwMDQ3MGVjNzYxMDg2ZmIwMmYwZjQ0ZDI1OTdmODdlNDNkZTdlOTZjMWJlMmNhMTZiZjlkNWIzNDliMjEzZTI)
