### ISSUE TITLE
[New Cohort] Programming Languages, Part A

### ISSUE THREAD

**Issue by hamzicabdulah** [ossu/cohorts#14]
## Class

Computer Science / Core Programming / Programming Languages, Part A

## Coordinators (1/3)

- [Abdulah Hamzic](https://github.com/hamzicabdulah)

## Students (1/20)

- [Abdulah Hamzic](https://github.com/hamzicabdulah)

## Start Date

April 16, 2018

## Slack Channel

Join the [OSSU Slack workspace](https://ossuniversity.slack.com), then find the channel #prog-languages-part-a.

**Comment by hamzicabdulah** [comment]
Yeah, completed it by myself, since no one was interested. That's actually the last OSSU course I did. Started Programming Languages B afterwards, but didn't end up completing it. What about you? Where are you currently in the curriculum?

**Comment by amorriscode** [comment]
@hamzicabdulah I've done up to How To Code: Complex Data. I'm starting Linear Algebra today! I took a break from OSSU to get some AWS certificates. 😀
