### ISSUE TITLE
Why is ossu using Slack instead of Gitter?

### ISSUE THREAD

**Issue by joshuaalm** [ossu/cohorts#15]
I'm only asking.  I am under the impression that Gitter is more open and community-based.  Of course, whatever we use should be accessible and always free, to whatever extent possible.

**Comment by amorriscode** [comment]
This was my bad I guess. I prefer Slack and use it for all of the projects I work on, so when I started doing cohorts it was natural for me to add an OSSU group. I am definitely for using Gitter instead, if that is what people prefer.

**Comment by joshuaalm** [comment]
I meant to comment earlier, but you know, life.  I really appreciated the earnest response!  I support your reasoning and if ever a move to Gitter makes more sense, I will be happy to help make the move or simply join you there!
