### ISSUE TITLE
[In Progress] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by amorriscode** [ossu/cohorts#2]
## Class

[Computer Science / Introduction To Computer Science / Introduction to Computer Science and Programming using Python](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-11)

## Coordinators (2/3)

- [Anthony Morris](https://github.com/amorriscode)
- [Valentin Prugnaud](https://github.com/foxted)

## Students (11/20)

- [Anthony Morris](https://github.com/amorriscode)
- [Valentin Prugnaud](https://github.com/foxted)
- [Todd Baylis](https://github.com/tdbaylis)
- [Vivek Poddar](https://github.com/vivekimsit)
- [Abdulah Hamzic](hamzicabdulah)
- [April Mulvey](https://github.com/mulvster)
- [Spencer Tranter](https://github.com/SpencerTranter)
- [Mikhail Kirillov](https://github.com/w96k)
- [Adam Clarkson](https://github.com/atclarkson)
- [Craig Kelleher](https://github.com/craigkelleher)
- [Sergio Camargo](https://github.com/scamargo)
- [Ukrit Pornpatanapaisarnkul](https://github.com/ukritp)

## Start Date

October 16th, 2017

[Please join our Slack channel.](https://join.slack.com/t/ossu-cs-cohort001/shared_invite/enQtMjU1OTYyNzc0MzA0LTAyOWI2YTY1MTM0MzY5YjY1NTA0ZmQ5ZTU0NjFlMzQ4ODZmMmQ3ZGMxYzViYjAyMTY2MGM2NGYxYWU3NGJkYWQ)

**Comment by foxted** [comment]
Valentin Prugnaud

**Comment by tdbaylis** [comment]
Todd Baylis

**Comment by vivekimsit** [comment]
Vivek Poddar

**Comment by ericdouglas** [comment]
Eric Douglas

**Comment by hamzicabdulah** [comment]
Abdulah Hamzic

**Comment by mulvster** [comment]
April Mulvey

**Comment by SpencerTranter** [comment]
Spencer Tranter

**Comment by amorriscode** [comment]
Hey everyone!

Monday is fast approaching and I just wanted to send you all a quick note prior to starting our class.

[Please make sure you register for the class on edX.](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-11) edX is a pretty good platform. If you want, you can buy the verification _but it is entirely optional_.

The class is broken up into **seven weeks**. Every week we will get together to discuss our learnings, difficulties, etc. We don't necessarily have to meet for a live chat, although I think that will be valuable.

Week 1 is **Python Basics**. Please complete the two lectures and problem set by **Monday, October 23rd, 2017**. We can have our discussions that Monday, prior to starting Week 2.

I have [created a Facebook group](https://www.facebook.com/groups/752107018325256/) for us to communicate on and discuss things we have learned or struggled with throughout the week. Please join that group, and if that doesn't work for you, we can open a discussion about what to do instead.

Let me know if you have any questions or if there is anything I can do for you! I look forward to learning with you all.

Cheers!

@SpencerTranter @foxted @mulvster @tdbaylis @vivekimsit @hamzicabdulah

**Comment by w96k** [comment]
Hey!
Can I join? I'm Mikhail Kirillov.

**Comment by amorriscode** [comment]
@w96k Yes of course! No worries about being late, entry to the cohort is possible _after_ it has started. Can you join the Facebook group?

**Comment by atclarkson** [comment]
I started CS50 when the 2017 fall semester started so I am on week 6 (7th week, CS jokers think it's funny to start with week 0) now.  We are out of C as of this week so according to OSSU I can move on this MIT 6.00 course.

My issue is that I want to keep going with CS50, I'm really enjoying it and also the completionist part of my brain is really wanting me to finish it, however, I see this cohort starting tomorrow and I really want to jump in with everyone here.

I'm considering starting 6.00 and continuing CS50 at the same time.

So I guess my question is, is anyone else in a similar situation? or does anyone think this is a really bad Idea.  I'd love to here everyone's thoughts.

-Adam

**Comment by amorriscode** [comment]
@atclarkson Hey Adam!

I am in the same boat as you. I'm almost done CS50 but I work as a web developer professionally, so I figured it was okay to skip the rest of the course and move on. It's was hard for me to accept at first, I like to complete things too, but I think it will be more fun moving through with a cohort.

Depends on your free time, you could probably do them both at the same time.

**Comment by atclarkson** [comment]
Alright! Count me in! I’ll just make 6.00 the priority and do what I can with CS50. Since they’re both python its either going to make it easier or be confusing as hell!

Put me on the list!

Adam Clarkson

**Comment by vivekimsit** [comment]
@amorriscode I am not comfortable with facebook group idea at all. Why not stick with gitter or github?

**Comment by hamzicabdulah** [comment]
I would suggest Slack as the best option for me personally. Not sure if everyone else would be fine with it

**Comment by atclarkson** [comment]
I don’t personally use Facebook so it’s not exactly convenient for me either but I have an account so I joined the group.

I’ve never used slack so can be up for trying that.  Or what ever the group wants.

**Comment by amorriscode** [comment]
Hey everyone, I agree about Facebook.

Here is the Slack invite: https://join.slack.com/t/ossu-cs-cohort001/shared_invite/enQtMjU1OTYyNzc0MzA0LTAyOWI2YTY1MTM0MzY5YjY1NTA0ZmQ5ZTU0NjFlMzQ4ODZmMmQ3ZGMxYzViYjAyMTY2MGM2NGYxYWU3NGJkYWQ

**Comment by craigkelleher** [comment]
Craig Kelleher, count me in!

**Comment by scamargo** [comment]
@amorriscode if you still want another coordinator, count me in
