### ISSUE TITLE
[New Cohort] Build a Modern Computer from First Principles: From Nand to Tetris

### ISSUE THREAD

**Issue by joshuaalm** [ossu/cohorts#21]
## Class

Computer Science / Core Systems / Build a Modern Computer from First Principles: From Nand to Tetris

## Coordinators (1/3)

- Joshua Marris

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- Joshua Marris

## Start Date

09/11/2018

**Comment by amorriscode** [comment]
Good luck Joshua! I would love to jump on this but it's a little short notice for me. :)

**Comment by joshuaalm** [comment]
Thank you for sharing your progress!  That's exciting.  I've been stuck on week 2, right up to building the APU.  I need to visualize it, but it's now been a year since I worked on the previous assignments, so I'm considering just starting over to have them fresh in my mind.  Work and family are taking up my time, but I will finish!

**Comment by amorriscode** [comment]
Hey, no worries there! I hope you don't mind that I closed the issue because you were doing the course alone and it has been a while. If you want to start over, feel free to make a new cohort!
