### ISSUE TITLE
[New Cohort] How to Code - Simple Data

### ISSUE THREAD

**Issue by empeje** [ossu/cohorts#23]
## Class

Computer Science / Core Programming / How to Code - Simple Data

## Coordinators (1/3)

- @empeje

## Students (9/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

1. @empeje
2. @gurungrahul2
3. @navimac (chapter 4 - 02/12/2018)
4. @Alaharon123 (chapter 1 - 03/12/2018)
5. @iamsahil1910
6. @g4m3rm1k3
7. @bradleygrant
8. @osanda-u
9. @crolaw
10. @zsesz 
11. @Hitchhiker90
12. @ismaelrumzan 
13. @Nazib3

## Start Date

Monday, 10 December 2018

**Comment by gurungrahul2** [comment]
Count me in as student.

**Comment by empeje** [comment]
> Count me in as student.

added @gurungrahul2

**Comment by navimac** [comment]
I am already on chapter 4 so I don't know if I am a fit for this group

**Comment by empeje** [comment]
I think for the sharing and support each other I'll add you as the student @navimac

**Comment by Alaharon123** [comment]
Count me in as a student. I'm already practically finished week one, but college is heating up so I'm not going to be very far ahead. I'll probably sync at week 3.

**Comment by empeje** [comment]
> Count me in as a student. I'm already practically finished week one, but college is heating up so I'm not going to be very far ahead. I'll probably sync at week 3.

@Alaharon123 added

**Comment by iamsahil1910** [comment]
Count me in as a Student.

**Comment by empeje** [comment]
> Count me in as a Student.

Added @iamsahil1910

**Comment by g4m3rm1k3** [comment]
I am just starting this class

**Comment by empeje** [comment]
> I am just starting this class

I'll count you as a student @g4m3rm1k3

**Comment by bradleygrant** [comment]
Sign me up. I'm finishing two other courses by 20 Dec, and I'm through the first week of HtC -- I should be able to track right along with you guys.

**Comment by empeje** [comment]
> Sign me up. I'm finishing two other courses by 20 Dec, and I'm through the first week of HtC -- I should be able to track right along with you guys.

added @bradleygrant

**Comment by empeje** [comment]
@amorriscode how we can organize cohort communication then?

**Comment by amorriscode** [comment]
There is a [Gitter channel](https://gitter.im/open-source-society/home) for all talk related to OSSU. You can see that there is a computer science room. If you wanted you could make one specifically for this group!

**Comment by empeje** [comment]
perhaps can we create a subchannel with the cohort number for example? so that people can support each other?

**Comment by amorriscode** [comment]
@empeje Under the channel I linked you can add rooms, so go ahead! 👍

**Comment by empeje** [comment]
<img width="624" alt="screen shot 2018-12-04 at 01 52 35" src="https://user-images.githubusercontent.com/11813607/49394767-55eba980-f767-11e8-9362-b16ee0efa00c.png">

no options for OSSU 😢

**Comment by amorriscode** [comment]
Oh, I see that now. I guess not anyone can create rooms! Sorry about that. I made a post in the Gitter chat. The best solution in this case would be to make your own community I guess.

**Comment by empeje** [comment]
I think it is okay to have room for each cohort **in the official community** so that they can focus on topics or a room for a specific course.

**Comment by g4m3rm1k3** [comment]
I have a discord channel for developement I could make a cohort channel https://discord.gg/k2v6xGz

**Comment by waciumawanjohi** [comment]
I saw the post in the gitter. Can I ask you to make an issue for it? https://github.com/ossu/computer-science/issues

I like the idea of having dedicated rooms for each cohort taking a course together.

@empeje : Here you suggested a gitter room for every _cohort_, while in the CS gitter you phrased this as a room for every _course_. I see this as very different idea, and one that I would not support. One of the challenges OSSU faced in the past was expanding to too many platforms, which meant there was never a critical mass on any platform for valuable conversation. A cohort is a structure that builds critical mass. Creating rooms for courses that often have sparse use does not help build critical mass.

Here are some past related issues that can provide further context:
https://github.com/ossu/computer-science/issues/495
https://github.com/ossu/computer-science/pull/497

**Comment by empeje** [comment]
hi, @waciumawanjohi I basically provide to options, if it's not possible to have room for each cohort, I think room for each course is sufficient.

**Comment by navimac** [comment]
@mpj I think You misunderstood  @waciumawanjohi
<https://github.com/waciumawanjohi>. As I understood he said that dedicated
channel for each cohort was good idea but having separate channel for each
course was bad idea in his opinion as it essentially dissolves student
concentration in each course and prevents any meaningful conversation. I
have to agree wit his position and also add that dedicated channel for each
course is also redundant as forum format in my opinion would be better
where issue in cohort would be posted and discussed by students. (this
model is applied in edx courses I too so far and works great.)

**Comment by navimac** [comment]
@mpj I think You misunderstood  @waciumawanjohi
<https://github.com/waciumawanjohi>. As I understood he said that dedicated
channel for each cohort was good idea but having separate channel for each
course was bad idea in his opinion as it essentially dissolves student
concentration in each course and prevents any meaningful conversation. I
have to agree wit his position and also add that dedicated channel for each
*cohort* is also redundant as forum format in my opinion would be better
where issue in cohort would be posted and discussed by students. (this
model is applied in edx courses I too so far and works great.)

Instead of course I meant cohort...

**Comment by waciumawanjohi** [comment]
@navimac glad to see that we agree on the disadvantage of creating a channel for every OSSU course.

On creating a gitter for each cohort: I like the idea because I hope that it can be fundamentally different from a forum.

You're correct that most OSSU courses contain message boards and that there's also this issues page. What I'm interested in seeing is if a cohort develops a true chat room: a place where for multiple hours everyday there are multiple people that are online and chatting, mostly about content, but often about life or interests or hardships.

I've seen that dual track at Georgia Tech, where my online courses have all had an official message board watched over by TAs and unofficial Slack channels where students joke around and yell out when they finish assignments.

Of course, that all depends on critical mass. Would the 7 of you be online often enough to make the chat room useful to you all? I don't know. But the hope is that cohorts can lead to more peer support than any past OSSU students have had.

**Comment by bradleygrant** [comment]
The other nice thing about a cohort model is, as you finish one class more or less together, you can start a new class more or less together. The cohort need not be a single-class arrangement; indeed, most real universities that use a cohort model expect one cohort to begin, enroll, progress and graduate together.

That may be asking a lot of this particular band of merry men, but hey, we may decide we like each other -- or at least enjoy mutual commiseration.

**Comment by navimac** [comment]
@waciumawanjohi <notifications@github.com>  I see Your point. I was
thinking about this idea in comparison to forum just for discussion about
some part of course topic but as You and @Bradley Grant suggest this would
add another dimension to OSSU followers something like a real college
experience and a chance to forge new friendships. This I support
wholeheartedly. Also one more thing pops out as a benefit from this.
Currently although we have gitter channel and every course has a discussion
forum I felt like a lone wolf in following OSSU curriculum but like every
other human activity programming is a collaborative field and this totally
differs from current study model. Maybe this idea will also help to bring
collaboration to our OSSU path.

**Comment by osanda-u** [comment]
I've just signed up so count me in as well, please.

**Comment by crolaw** [comment]
I just signed up so add me too.

**Comment by empeje** [comment]
Temporarily lets use https://gitter.im/OSSU-empeje/cohort23 as a cohort communication

@gurungrahul2
@navimac (chapter 4 - 02/12/2018)
@Alaharon123 (chapter 1 - 03/12/2018)
@iamsahil1910
@g4m3rm1k3
@bradleygrant
@osanda-u
@crolaw

**Comment by zsesz** [comment]
I'd like to join. I'm halfway through week 1, but I'll try to catch up.

**Comment by Hitchhiker90** [comment]
Hi guys,

I'd also like to join and try to keep up with you.

**Comment by empeje** [comment]
Hi @zsesz and @Hitchhiker90 you're welcome

**Comment by ismaelrumzan** [comment]
Please sign me up as a student

**Comment by empeje** [comment]
sure @ismaelrumzan added

**Comment by Nazib3** [comment]
Count me in as student please

**Comment by empeje** [comment]
@Nazib3 done

**Comment by fandikaikhsan** [comment]
just curious, is anyone has completed all of the ossu course?

**Comment by fandikaikhsan** [comment]
btw count me in, just finished week 3 lol

**Comment by Alaharon123** [comment]
We were just talking about it on the Gitter and four people reported in with their progress, which ranges from end of week 3 to starting of week 6. Scroll up for the link to join the Gitter.

**Comment by ifprado** [comment]
I'd like to join

**Comment by M1c17** [comment]
add me please Telegram: m1c17

**Comment by Alaharon123** [comment]
We're not on Telegram, that's the MIT 6.00.1x cohort. We're on Gitter, scroll up a bit to find the link. The chat has been pretty dead for a bit, but I think people are there, just not very active. You should get responses if you ask any questions or just chat. It would be up to @empeje to actually edit you into the original post (idk how active they are), but participating in the Gitter makes you as much a member as anyone else imo.

**Comment by ahmeed83** [comment]
Guys, are you still following this course? I just opened a new issue of anyone wants to join me

**Comment by amorriscode** [comment]
@empeje can I close this issue? I'm assuming you are done with it as the Gitter is dead.
