### ISSUE TITLE
[New Cohort] Introduction to Computer Science - CS50

### ISSUE THREAD

**Issue by G-Ox7cd** [ossu/cohorts#24]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science - CS50

## Coordinators (1/3)

- Gurram Prashanth

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- Add students here

## Start Date

_Choose a start date for your cohort. We suggest providing two weeks for other students to join._

**Comment by amorriscode** [comment]
@G-Ox7cd when are you planning to start this class?

**Comment by mraza007** [comment]
I’ll be the coordinator

**Comment by CamLV** [comment]
I just started CS50 yesterday. What do I do to participate?

**Comment by CamLV** [comment]
I find my self unable to continue. Sorry.

**Comment by crolaw** [comment]
I am interested.

**Comment by hansolo0210** [comment]
I am interested. Already started CS50. How do we proceed?

**Comment by wohlner** [comment]
I am also interested. @mraza007, thanks for volunteering to be the coordinator. Do you have any advice for getting this cohort started or how and when to begin?

**Comment by EmKhay** [comment]
I am interested as well, how do I join this co-hort? if possible?

**Comment by theRealAbdurrahman** [comment]
I'm excited and interested, Did you start this cohort?

**Comment by cinephile85** [comment]
I'm looking to start CS50 in about a week, and would like others to learn with. Anyone have any details about this cohort or when it might start? If someone wants to lead, is there any interest in opening a new issue?

**Comment by narayanansriram** [comment]
Hey guys! Me too! I am about 3 weeks in right now

**Comment by cinephile85** [comment]
If anyone has ideas on how to coordinate things, I'll gladly start a new cohort.

**Comment by JhamereWilson** [comment]
I've already started the course. How might I go about being added as a student?

**Comment by amorriscode** [comment]
Hey everyone. @G-Ox7cd seems like he isn't active so I am going to close this issue. Hopefully someone else can make a new one and coordinate the class. Perhaps @mraza007 is interested?
