### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by CodebyKhayla** [ossu/cohorts#25]
Official Class on edx starts Jan 19th 2019 if anyone wants to join 😁

Update/Edit: 

**Class**
Computer Science / Introduction To Computer Science / [Introduction to Computer Science and Programming using Python](https://www.edx.org/course/introduction-to-computer-science-and-programming-using-python-0)

**Coordinators** (2/3)
[Khayla Matthews](https://github.com/emKhay)
Prashant Kumar
This co-hort is merging with another, see thread #26 for more information.

**Students** 
This co-hort is combined with #26 for a maximum of 40 students. 

**Start Date**
Tuesday, 22th Jan 2019

**Communications** 
Students in both this co-hort and the concurrent one (#26) can communicate, share resources, ask questions (and so on) adding one of the coordinators and joining the Telegram group.

**Comment by Ozone86** [comment]
Count me in!

**Comment by TimTheDM** [comment]
Howdy and happy new years! I've signed up for that class on edX for the 22nd, and I'd love to join this cohort.

**Comment by EmKhay** [comment]
Hello! Thanks and same to you. 
Awesome! Thanks for joining!

**Comment by LetsLearnCS** [comment]
I'm in! Just starting the OSSU CS program and learning all about it this evening. I need to also brush up on and learn additional math. I wish everyone success on their journey.

**Comment by EmKhay** [comment]
@LetsLearnCS  Great! nice to meet you, LetsLearnCS! I'm just starting as well and still learning. I'm actually going to be spending the next few months trying to get my math skills up - I don't know where you are in your math journey, but on edx, there is a college algebra course through Arizona State and there is also a "Pre-University Calculus" course. I'm going through the college algebra course, since I'm afraid to just jump in with the calc given my weak algebra and non-existent trig skills. 

If you'd like to join me in the algebra course, let me know, I'm only about halfway done. Maybe even a little less.

**Comment by LetsLearnCS** [comment]
@EmKhay :D nice to meet you too. I'm going to start brushing up on math by jumping on Khan Academy to play around and see where I'm at. I will let you know if I decide to take that course. Thank you for the offer!

**Comment by EmKhay** [comment]
@LetsLearnCS No problem! I did the same thing, completely understand.

**Comment by undercoveruss** [comment]
hey i am also interested guys.

**Comment by EmKhay** [comment]
@undercoveruss awesome! 

This is a question to everyone, how will we keep in touch during the co-hort and are we all intending to spend the same amount of time on it?

**Comment by undercoveruss** [comment]
@EmKhay I have also created co-horts issues-26.
https://github.com/ossu/cohorts/issues/26

**Comment by undercoveruss** [comment]
Can we merge both co-horts 25 and 26 together.

**Comment by HaroldAFG** [comment]
Hi everybody!! I would like to start this class with you.

**Comment by EmKhay** [comment]
@undercoveruss
How did we end up with two co-horts?

**Comment by undercoveruss** [comment]
@EmKhay 
We can create common group like on discord or any other platform with both #25 and #26 participants.

**Comment by EmKhay** [comment]
@undercoveruss 

I had never looked into Discord before, it seems like it is for gamers. But it is an option. 
What about a Slack group?

**Comment by undercoveruss** [comment]
@EmKhay 
It's a good option and telegram also a good option.

**Comment by EmKhay** [comment]
@undercoveruss
Just googled and Telegram might be the best option.

**Comment by undercoveruss** [comment]
@EmKhay 
okay, than we can create private telegram group with both #25 and #26 participants.

**Comment by HaroldAFG** [comment]
my Telegram user name is haroldfandino

**Comment by cavanzo1996** [comment]
Hello world XD, my username is @Cavanzo

**Comment by siegfried3991** [comment]
Hello everyone, my Telegram username is siegsin, new to here and programming too, so hope we can study together!

**Comment by Rachiddreamer** [comment]
Guys I want to join please!

**Comment by johnotu** [comment]
Just found OSSU. What a fantastic initiative! Would like to join this cohort. I'm on Telegram as _johnotu_

**Comment by EmKhay** [comment]
@johnotu
Check your privacy settings. 

I'm not sure how to do that. @undercoveruss maybe...

**Comment by undercoveruss** [comment]
@johnotu Please, just try to change your privacy settings of telegram. Steps to follow.
Settings> Privacy and Security> Groups> My Contacts to Everybody.

**Comment by johnotu** [comment]
Thank you @undercoveruss for the steps. It's done.

**Comment by EmKhay** [comment]
@undercoveruss thanks!

**Comment by Rachiddreamer** [comment]
already commented here, but no response!
Could you please add me.
My telegram is@Dido Suicide

**Comment by EdaurdoCS93** [comment]
I want to join

**Comment by amorriscode** [comment]
@CodebyKhayla how's it going? Has this course been completed? I'd like to close out the issue if so. 😀

**Comment by CodebyKhayla** [comment]
Hello! I have to retake the class, but yes this iteration of it is done. 😅
