### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by undercoveruss** [ossu/cohorts#26]
># **_OSSU/COMPUTER SCIENCE (2019-BATCH)_**

## Class

Computer Science / Introduction To Computer Science / [Introduction to Computer Science and Programming using Python](https://www.edx.org/course/introduction-to-computer-science-and-programming-using-python-0) 
Extra Course- [Introduction to Computing in Python](https://www.edx.org/professional-certificate/introduction-to-computing-in-python)

## Coordinators (2/3)

- [Prashant Kumar](@undercoveruss)
- [Khayla Matthews](@EmKhay) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))

## Students (26/30)

_We are combining students of both cohorts #25 and #26 together minimum of 5 students with no more than 20._

- [Prashant Kumar](https://github.com/undercoveruss)
- [Khayla Matthews](https://github.com/EmKhay) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [Suraj Branwal](https://github.com/brandier-jd)
- [Harold Fandiño](https://github.com/HaroldAFG) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [Luis Eduardo Cavanzo](https://github.com/cavanzo1996) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [Timothy Smithlin](https://github.com/TimTheDM) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [Ahmad Mustafa](https://github.com/ahmadmust8)
- [Dan Kreiger](https://github.com/dankreiger)
- [Siegfried Sin](https://github.com/siegfried3991) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [Bryan Rinders](https://github.com/BryanRi )
- [Kevin Klik](https://github.com/Klik01)
- [Will Harris](https://github.com/willharris1)
- [Arnaud Thev](https://github.com/Bukowsky)
- [Mursalin Kabir](https://github.com/murs007)
- [Ahmed Sheta](https://github.com/AhmedShetaa)
- [Rachid](https://github.com/Rachiddreamer) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [John Otu](https://github.com/johnotu) - ([Co-horts #25](https://github.com/ossu/cohorts/issues/25))
- [Mohamed Ahmed](https://github.com/bazedy)
- [Nikhil Bhure](https://github.com/bhure)
- [Benjamin](https://github.com/Pyhscript)
- [Dex](https://github.com/TheHuskyena)
- [Aziz Maknojia](https://github.com/mak-aziz)
- [Zack](https://github.com/zhornbe)
- [Waleed Ghazy](https://github.com/Waleed-Ghazy)
- [ZhenYi-Lim](https://github.com/ZhenYi-Lim)
- [Lauren McClure](https://github.com/amadeus8)

## Start Date

_Tuesday, 22nd Jan 2019_

## *We will be using telegram group for interactions and queries.*
_If you are using telegram then comment your username and you are new to telegram then create your telegram account first._
> ### [Telegram](https://telegram.org/)

**Comment by brandier-jd** [comment]
Suraj Branwal

**Comment by undercoveruss** [comment]
Hey @EmKhay can you share your telegram username.

**Comment by EmKhay** [comment]
@undercoveruss I just tried Discord and I actually liked it better. haha. My telegram username is the same as here.

**Comment by ahmadmust8** [comment]
hello, I'm also looking for group to stady with , 
I gann start the first course in 22 Jan.
please can you add me to your Telegram group? 
my user name in Telegram is : Ahmad Mustafa

**Comment by undercoveruss** [comment]
@ahmadmust8 Please provide your proper username. So, I can add you. Your provided username is your name.

**Comment by bazedy** [comment]
I am new I could you add me

**Comment by undercoveruss** [comment]
@bazedy please provide telegram username with your full name.

**Comment by bazedy** [comment]
@Bazedy

**Comment by dankreiger** [comment]
Is there anymore room in this cohort? My telegram username is @dankreiger - my name is Dan Kreiger lol. 

If there's no room, that's fine. I just wanted to ask.

**Comment by undercoveruss** [comment]
@bazedy Please, also provide your name.

**Comment by BryanRi** [comment]
I would like to join the telegram group if it's possible. Username is @BryanRi my name is Bryan Rinders.

**Comment by undercoveruss** [comment]
@BryanRi I am not able to find you on telegram. Please verify your username once again on telegram.

**Comment by BryanRi** [comment]
Ahh, I just created a telegram account and didn't noticed I hadn't created a username yet. Try it again @BryanRi.

**Comment by Klik01** [comment]
My telegram is @Klik01 and my name is Kevin Klik.

**Comment by willharris1** [comment]
hey all, I want to join the cohort and my telegram is @WillHa.  My name is Will Harris

**Comment by Bukowsky** [comment]
Hi all,
I would like to join this cohort.
I am already enrolled in GTx  Introduction to Computing in Python II and aim to finish the 4 parts.
I will also start MIT  Introduction to Computer Science and Programming using Python in Janv 22.

My username on Telegram is @Arnaud55.

Thanks

**Comment by murs007** [comment]
Hello, 
I'm Mursalin from Bangladesh. If it's possible, I'd like to join this cohort. My telegram username is @murs007. 
Thanks.

**Comment by AhmedShetaa** [comment]
Hello,
I'm Ahmed Sheta From Egypt, If it's possible I'd like to Join as well, my Telegram is: @MightySheta

Thank you.

**Comment by Rachiddreamer** [comment]
I already commented here, but no response!
Could you please add me.
My telegram is@Dido Suicide.

**Comment by amadeus8** [comment]
Hihi! Is there still room in this cohort? Could I please be added? Telegram is: @amadeus8.

Thanks!

**Comment by undercoveruss** [comment]
@amadeus8 Your name please.

**Comment by amorriscode** [comment]
Looks like today is the start date! This is easily the biggest cohort we have seen (new year, new you?) so I'm very excited to see how it goes. Good luck everyone!

**Comment by Alaharon123** [comment]
I'm not even part of the cohort, but I was bored in the break between semesters so I hung out in r/learnprogramming and recommended OSSU and this cohort where appropriate. I don't know how much that contributed, but I'm taking all the credit.

**Comment by ZhenYi-Lim** [comment]
Is it too late to join? My telegram is @ZhenYiLim

**Comment by Waleed-Ghazy** [comment]
just saw this now @Waleed_Essam
my name is Waleed Essam
I already started the course and finished week 1

**Comment by EmKhay** [comment]
@Waleed-Ghazy Thanks for your information. I think we might have reached the maximum 20 students for this co-hort (they may not all be listed in this thread as of yet, due to how quickly students signed up), but I'm going to check with the other admins though to be sure. Someone will get back to you soon.

**Comment by hatboxghost** [comment]
If there is still space, I would like to sign up for this cohort.

**Comment by EmKhay** [comment]
@hatboxghost 
Hello! Thanks for your interest in joining this co-hort.
Someone will get back to you soon.

**Comment by EmKhay** [comment]
@Waleed-Ghazy @hatboxghost Great news, I got clarification and we have definitely have room for you guys. Sorry about that. 
Waleed-Ghazy, you have been added to the Telegram group. 
hatboxghost, please provide your Telegram username so we can add you to the group.

**Comment by mak-aziz** [comment]
Is there still space? I would like jump right in!

**Comment by mak-aziz** [comment]
it's @mak_aziz @EmKhay. Thank you!

**Comment by TheHuskyena** [comment]
If there's still room for me I'd like to join. My Telegram is @TheHuskyena.

**Comment by EmKhay** [comment]
@TheHuskyena Thanks for providing your telegram username. We will add you to the group.

**Comment by Pyhscript** [comment]
Hi if there's more place left by any chance I'd love to be added, my name is Benjamin and my telegram is @Pyhscript

**Comment by EmKhay** [comment]
You're all set, Benjamin. @pyhscript

**Comment by bhure** [comment]
Hello , if by chance any spot is still left please add me too 
My name is Nikhil 
And telegram handler is @cold3r

**Comment by kylebalcerski** [comment]
I'm also enrolled in this class, finishing up week 1 now. If this cohort isn't too saturated I'd like to join. My telegram is @kylebalcerski, name is Kyle Balcerski.

**Comment by simonecicognani** [comment]
Hello, I've started this course some days ago.
Is still possible to join? Telegram: @SimoneCicognani

**Comment by M1c17** [comment]
Telegram: @m1c17

**Comment by NoActualName** [comment]
Would like to join the group - just recently started the course and would appreciate having others to learn together with. 

Telegram username: @NoActualName

**Comment by dhairyadwivedi** [comment]
Hi! I'm just starting out, is it too late to join this group?

**Comment by petermcc212** [comment]
If not too late, I'd like to join this cohort too! 
My username on Telegram is @petermcc1212
Thanks!

**Comment by DrAbdelmoneem** [comment]
Please I would like to join the cohort as a student 
my username on Telegram is @Elmeligy I already watched many course videos but unfortunately I've  just read about cohorts

**Comment by Mamand77** [comment]
Hello 
My name is Mamand Abdullah
I'd like to join to this cohort as a student 
my user name is @MamandRMamand
thank you

**Comment by CodebyKhayla** [comment]
I believe this class is just about done on Edx. There is a second iteration
of the class starting in June.

**Comment by guidoti** [comment]
I'll start this course in June as well. Should we create a new co-hort?

**Comment by dhairyadwivedi** [comment]
Yeah, let's do that if everyone's okay with it?

**Comment by dhairyadwivedi** [comment]
I'll create a group on telegram then! Lemme know if you wanna join :)

**Comment by guidoti** [comment]
I do, but we also need to create a cohort here. There is a cohort generator somewhere that you can use... We need a cohort coordinator and etc. Can you do it?

**Comment by murs007** [comment]
Hey, please add me @murs007. I'll probably give the final exam again in the upcoming course. I did take the recent one except the final exam.

**Comment by mguidoti** [comment]
@mguidoti here ;)

**Comment by dhairyadwivedi** [comment]
I've a full-time job which takes up a lot of my time so I'm not really up to being a cohort coordinator, anyone else up for it?

**Comment by murs007** [comment]
I can give it a try.

**Comment by dhairyadwivedi** [comment]
Added @murs007, @mguidoti - unable to add you, user not found. If anyone else wants to join please leave you username here and I'll add you.

**Comment by ikejosh** [comment]
Hello, I would like to join this cohort and my telegram username is @NotJohs

**Comment by saphal1998** [comment]
I would love to join this cohort as well.  My telegram username is @saphal1998

**Comment by kkviks** [comment]
Telegram username : **@kkviks**

**Comment by Klik01** [comment]
Remove me from this damn group.

**Comment by TolkienRools** [comment]
I would like to join the cohort as a student
my username on Telegram is @rosvell

**Comment by Lu-design** [comment]
Hello, I am starting the course "introduction to computer programming using python" that started yesterday, 28th August.

could I join this cohort or create a new one?

telegram name @gluniverse
