### ISSUE TITLE
[New Cohort] Build a Modern Computer from First Principles: From Nand to Tetris

### ISSUE THREAD

**Issue by M1c17** [ossu/cohorts#28]
## Class

Computer Science / Core Systems / Build a Modern Computer from First Principles: From Nand to Tetris

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- Add students here

## Start Date

_Choose a start date for your cohort. We suggest providing two weeks for other students to join._

**Comment by amorriscode** [comment]
@M1c17 Please fill out the issue (ie: add your name under coordinator/student, choose a start date). Thanks!

**Comment by dexhunter** [comment]
@M1c17 Hi! I am also taking this course, would love to join the cohort as a student. Thank you!

**Comment by Elias-Urquiza** [comment]
Hi! I'm planning on taking this course and have already registered as an audit. I'd like to join the cohort as a student. Thanks!

**Comment by tthero** [comment]
Interested in joining this cohort as student. Thanks!

**Comment by G-Ox7cd** [comment]
What should be first done to join the cohort
??

**Comment by amorriscode** [comment]
@M1c17 Are you still doing this course? I'd like to confirm your engagement with the community. Many people want to be added as students and you have not filled out the issue properly. If you don't respond, I'll close this issue and have someone else create a new cohort. Thanks!

**Comment by JhamereWilson** [comment]
Interested in joining this cohort.
