### ISSUE TITLE
[New Cohort] How to Code - Simple Data

### ISSUE THREAD

**Issue by ahmeed83** [ossu/cohorts#30]
## Class

Computer Science / Core Programming / How to Code - Simple Data

## Coordinators (1/3)

- Ahmed Aziz

## Students (0/10)

- @ahmeed83
-  @mhmtaliakbay

## Start Date

6-4-2019

**Comment by Waleed-Ghazy** [comment]
Well I finished it but it will be a good idea to review it with other people and finish the final project as I still didn't get to do it

**Comment by ahmeed83** [comment]
How did you find it? Was it worth it?

Shall we make a slack group to discuss our progress?

**Comment by mhmtaliakbay** [comment]
hi can you add me

**Comment by ahmeed83** [comment]
yes sure mhmtaliakbay

**Comment by alnav** [comment]
Hello, I'm halfway through the course and it has been great so far. It would be nice to share and discuss progress with you guys. How do I join the group?

**Comment by ahmeed83** [comment]
Hey Alnav, yes sure! Shall we make a slack group so that we can talk and discuss?

**Comment by ahmeed83** [comment]
https://join.slack.com/t/ossugroup/shared_invite/enQtNjMzNjI0MjM0NjQ2LTRjYTBiZDYyZTRhNTJiY2JlZGNhMWQzZjg3MzBiNTlkMjg2YzU5MjQ0NTcwNzEwN2U1YzBiYTI5NzZjNWU3MzM

**Comment by ahmeed83** [comment]
i just shared a link where you guys can join for the slack group

**Comment by ravicma** [comment]
hey i would like to join :)

**Comment by ahmeed83** [comment]
Hey Ravicma, sure you are welcome. Just click on the link and you can join our slack channel

**Comment by ahmeed83** [comment]
https://join.slack.com/t/ossugroup/shared_invite/enQtNjMzNjI0MjM0NjQ2LTRjYTBiZDYyZTRhNTJiY2JlZGNhMWQzZjg3MzBiNTlkMjg2YzU5MjQ0NTcwNzEwN2U1YzBiYTI5NzZjNWU3MzM

**Comment by megaweedle** [comment]
Hi, I'm interested in joining this cohort if it's still active

**Comment by Kun17** [comment]
Wow, anyone still here?

**Comment by alnav** [comment]
I am!

**Comment by amorriscode** [comment]
I'm closing out this cohort as it is quite old.
