### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by murs007** [ossu/cohorts#31]
## **Class**

Computer Science / Introduction To Computer Science / [Introduction to Computer Science and Programming using Python](https://www.edx.org/course/introduction-to-computer-science-and-programming-using-python-2)

## Coordinators (1/3)

- [Mursalin Kabir](https://github.com/murs007)

## Students (28/20)
This is a new cohort for MITx 6.00.1, started on June 5, 2019. We'll be taking around 20 students for this cohort. Comment below to get yourself added.
* We're already 28.

- [Marcus Guidoti](https://github.com/mguidoti)
- [Dhairya](https://github.com/dhairyadwivedi)
- [CodebyKhayla](https://github.com/CodebyKhayla)
- [jennyn0va](https://github.com/jennyn0va)
- [kg-constant](https://github.com/kg-constant)
- [calebcarithers](https://github.com/calebcarithers)
- [Pobs97](https://github.com/Pobs97)
- [Rachel Curioso](https://github.com/Rachc)
- [Wallace Barnes](https://github.com/nodakbarnes)
- [pasko00](https://github.com/pasko00)
- [Wajdi Ben Abderrahmen](https://github.com/wajdTECH)
- [shoalcellos](https://github.com/shoalcellos)
- [Johs](https://github.com/ikejosh)
- [mediocreative](https://github.com/mediocreative)
- [danbros](https://github.com/danbros)
- [ravicma](https://github.com/ravicma)
- [Amiraliiscool](https://github.com/Amiraliiscool)
- [Joseph Owonvwon](https://github.com/owonwo)
- [khadijaNur](https://github.com/khadijaNur)
- [Staley](https://github.com/sStaley23)
- [Muhammad Abdullahi](https://github.com/qsim98)
- [Odika Emmanuel Chinedu](https://github.com/Life-Hex)
- [Kirill Shakhansky](https://github.com/FuzzzzyBoy)
- [Abdelaty Mohammedmagdi Abdelaty](https://github.com/Abdelaty)
- [Trisha Aguinaldo](https://github.com/kronicle114)
- [craiglaurences](https://github.com/craiglaurences)
- [PLChinDev](https://github.com/PLChinDev)
- [FamousAmos](https://github.com/FamousAmos)

* The course has already started.

Telegram group will be used primarily for interactions and queries.
If you are using telegram, please comment your username. Alternatively, if you are new to Telegram, you can create your account easily following the link below.

**Comment by jennyn0va** [comment]
Hi, I'd like to join the please

**Comment by murs007** [comment]
Please let me know your telegram ID @jennyn0va

**Comment by jennyn0va** [comment]
same as here: jennyn0va

**Comment by mguidoti** [comment]
Awesome @murs007 ! 

Thanks for taking the lead and creating the cohort. Here's my telegram ID: mguidoti.

**Comment by kg-constant** [comment]
Hi, I'd be pleased to be added to tho cohort
Here is my ID: @kg_constant

**Comment by murs007** [comment]
Sure @kg-constant

**Comment by kg-constant** [comment]
Thanks! I look forward to starting this journey with the cohort. Thanks!

**Comment by calebcarithers** [comment]
Would love to join. Telegram ID: calebcarithers

**Comment by Pobs97** [comment]
I'd like to join. Telegram ID: @Pobs97

**Comment by Rachc** [comment]
Hello, I'd like to join, please (: 
my telegram id is **@rachcl**

Thank you!

**Comment by nodakbarnes** [comment]
Please add me...thanks!
**@nodakbarnes**

**Comment by pasko00** [comment]
Hello! Is this cohort open ? I would like to join :)
**@zube91**

**Comment by wajdTECH** [comment]
I would like to join too, my telegram id: @wajdi_tn

**Comment by shoalcellos** [comment]
Hello, I'd like to join also.

Telegram ID: @shoalcellos

**Comment by mediocreative** [comment]
Hey, I would like to join your cohort :> 
Telegram ID : @madisovetov.

**Comment by danbros** [comment]
Omg, this is real!
I'm ready, let me join you
@dan_bros

**Comment by ravicma** [comment]
I would like to join :) 
@rvcmco

**Comment by Amiraliiscool** [comment]
Hey, I would like to join your cohort :>
Telegram ID : @ @ @ @ @ @ @ @k1t3une

**Comment by FamousAmos** [comment]
Hello, I would like to join the cohort.

Telegram ID: @FunnyFamous

**Comment by PLChinDev** [comment]
Please include me as a student. Telegram ID: @PLChinDev

**Comment by ashimapanjwani** [comment]
I'd like to join. Telegram ID: @ashimapanjwani

**Comment by khadijaNur** [comment]
Hello,I'd like to join please.
Telegram ID:@khadijaNur

**Comment by sStaley23** [comment]
Hello, I would like to join as well
Telegram ID: @packPariah

**Comment by qsim98** [comment]
I would like to join, 
Here is my ID : @mksim

**Comment by qsim98** [comment]
I would like to join, 
Here is my Telegram ID : @qsim98

**Comment by Life-Hex** [comment]
Please include me.
Telegram: @MannyX7

**Comment by FuzzzzyBoy** [comment]
Hi. Can I join you? @FuzzzzyBoy

**Comment by Abdelaty** [comment]
I'd like to join

**Comment by kronicle114** [comment]
Hello,I'd like to join please.
Telegram ID:@kronicle114

**Comment by craiglaurences** [comment]
Hi, I’d like to join this adventure ... would you kindly?
Telegram ID:@craiglaurence

**Comment by vjavs** [comment]
Hi, I'm in!
Could you please add me?
Telegram ID: @viniciusjavs

**Comment by AuntieGame** [comment]
I see you're over capacity for students on this one, but the other cohort for this course with members seems inactive. Should I wait for activity on that cohort, or may I join this one? 
Telegram ID:@auntiegame

**Comment by fahmydiab** [comment]
I would like to join

**Comment by prabuinet** [comment]
add me please tel id: prabuinet

**Comment by Lu-design** [comment]
Hello, I am starting the course "introduction to computer programming using python" that started yesterday, 28th August. 

could I join this cohort or create a new one? 

telegram name @gluniverse

**Comment by amorriscode** [comment]
I'm closing out this cohort as it is quite old.
