### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by mabobakr86** [ossu/cohorts#33]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science and Programming using Python From The MIT Opencourseware

## Coordinators (1/3)

Mohamed Abobakr

## Students (0/10)

# 
19 May 2019

**Comment by mabobakr86** [comment]
Let`s get started With Our Computer science Journey from the Beginning, This is the 1st Course "Introduction to computer science using Python" and we`ll start it from the MIT Opencourseware , It is the same material as the Edx Course and it will cover The Concepts in python 3.5 Too so lets start 
and here is the link to the Course 
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/index.htm

**Comment by amorriscode** [comment]
@mabobakr86 this cohort is a duplicate. I'm closing this in favour of #31. Thanks for understanding!
