### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by Abdelaty** [ossu/cohorts#34]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science and Programming using Python

## Students (5/5)

- @AhmedElmasry700
- @AlaaElrhmanArafa
- @abdelaty
- @wandersonrossi
- @Ganesh003
## Start Date

_5 June_

**Comment by AlaaElrhmanArafa** [comment]
...

**Comment by AhmedElmasry700** [comment]
..

**Comment by ganesh003** [comment]
for the role of student.

**Comment by WandersonRossi** [comment]
I would like to join as a student!

**Comment by Abdelaty** [comment]
@WandersonRossi  @ganesh003 
Kindly join the whatsapp chat group 
https://chat.whatsapp.com/FH35cj24eisBar9R3vrpRM

**Comment by shabbamm** [comment]
Joining in as a student 💯

**Comment by AuntieGame** [comment]
I'd like to join as a student, please.

**Comment by amorriscode** [comment]
I'm closing this cohort as it is quite old.
