### ISSUE TITLE
[New Cohort] Introduction to Computer Science - CS50

### ISSUE THREAD

**Issue by dev-grrl-japan** [ossu/cohorts#36]
#36 Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science - CS50

## Coordinators (3/3)

- Nahtym (Jojo!)
-Peter @petermcc212
- @celorhmbib56

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

## Start Date: July 1st

Hello, all! Welcome to the CS50 2019 Mid-summer cohort! I'm Jojo and am excited to complete the CS50 course together! 
I was hoping to make this a group to help with studying for the CS50 2019 Lectures and Labs as well as to develop a FINAL project together! 

As for communication and assignment of tasks, I was thinking via Discord, Git, Github, and Trello for task MGMT. 
Any ideas, comments, suggestions, please send this way! If you wanna join feel free to comment below!

I'm looking forward to working with you!!

Jojo

**Comment by petermcc212** [comment]
Hi, I'd like to join this cohort please.

**Comment by nahtym** [comment]
> Hi, I'd like to join this cohort please.

Hello Peter! Welcome!

**Comment by celorhmbib56** [comment]
Kindly add me to your cohort.

**Comment by nahtym** [comment]
> Kindly add me to your cohort.
Welcome!

**Comment by nahtym** [comment]
Hi @petermcc212 and @celorhmbib56 ! Shall we get started on this project? I was thinking we could do a CS50 study group online foor weeks 0-11 while planning for the final project together!

All in favor say aye!
But to do this I think we need a way to collaborate virtually. 

I was thinking of seting up a trello board or tracking progress via monday.com .
Do you all have any other ideas to help create a virtual collab enviornment? 

Also, do you all have a preferred way to stay in contact? I was thinking through google hangouts would be pretty efficient. We could do a group meeting every week about the final/ study session. 

Let me know what you all think!

**Comment by MainaKamau92** [comment]
Hello @nahtym I'd also like to join the cohort if possible.

**Comment by dreibelbisaurus** [comment]
@nahtym, looks like you might be the only active one. Did anyone else join you? I'd love to.

Thanks!

**Comment by AhmedGamal1496** [comment]
I'm ready to join. I am doing pset3 at the moment.

**Comment by petermcc212** [comment]
@nahtym, sorry I have work commitments that mean I can't take part in the project. Apologies for wasting your time

**Comment by VuGeorgeEddie** [comment]
Heya guys, is this cohort still up n running. id be up for trying to do this. @nahtym

**Comment by ericafenyo** [comment]
Ready to join please.  @ericafenyo

**Comment by xb3sox** [comment]
@nahtym 

Hi Jojo, 

Did you start?,  I want to join.

Thanks

**Comment by xb3sox** [comment]
@nahtym @celorhmbib56

Hi Guys,

Did you start?, I want to join.

Thanks

**Comment by ssardana08** [comment]
Hi, I'd like to join this cohort please.

**Comment by st1drako** [comment]
Hello, I`d like to join the cohort if it`s possible, thanks

**Comment by amorriscode** [comment]
I'm closing this cohort as it is quite old.
