### ISSUE TITLE
[New Cohort] How to Code - Simple Data

### ISSUE THREAD

**Issue by amorriscode** [ossu/cohorts#4]
## Class

[Computer Science / Core Programming / How to Code - Simple Data](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x)

## Coordinators (1/3)

- [Anthony Morris](http://github.com/amorriscode)

## Students (7/20)

- [Anthony Morris](http://github.com/amorriscode)
- [Adam Clarkson](http://github.com/atclarkson)
- [Deepak Kushwaha](https://github.com/netship02)
- [Nikos Panaiotu](https://github.com/Nixerrr)
- [Abdulah Hamzic](https://github.com/hamzicabdulah)
- [Vivek Poddar](https://github.com/vivekimsit)
- [Walter Vargas](https://github.com/waltervargas)

_Post a comment below if you'd like to join!_

## Start Date

December 11, 2017

## Slack
[Join the Slack group here](https://join.slack.com/t/ossuniversity/shared_invite/enQtMjc1Njk0MDk5NDc4LWM1OTkwNjg5YmMxZWVlNzJjMTRmYTU0NjhiNDZmZTE0MjgzOTdiZjZlYmQ0MzI5ZTBkZDI4N2YwMDk5NDM1MmI), we have a channel called `#howtocode-sd-001`!

**Comment by atclarkson** [comment]
Adam Clarkson

**Comment by Nixerrr** [comment]
Nikos Panaiotu

**Comment by Nixerrr** [comment]
(deleted my comment because I just realized that I will be well into the course by Dec 11.)

**Comment by netship02** [comment]
I am currently at week 4.

**Comment by amorriscode** [comment]
@Nixerrr How's the course going? I will update this post tonight with the Slack channel we have for OSSU. You'd be more than welcome to join to follow along with us, provide help, or just meet some other OSSU students!

**Comment by Nixerrr** [comment]
Sounds good, I'm in! I haven't gotten as far as I expected anyway - I'm at the end of 1B. Add me to the roster, please. :)

**Comment by hamzicabdulah** [comment]
Abdulah Hamzic

**Comment by vivekimsit** [comment]
Vivek Poddar

**Comment by amorriscode** [comment]
Hey everyone! Class starts Monday! I hope you're all as excited as I am. Please [join the Slack group](https://join.slack.com/t/ossuniversity/shared_invite/enQtMjc1Njk0MDk5NDc4LWM1OTkwNjg5YmMxZWVlNzJjMTRmYTU0NjhiNDZmZTE0MjgzOTdiZjZlYmQ0MzI5ZTBkZDI4N2YwMDk5NDM1MmI) and find our channel: `#howtocode-sd-001`!

**Comment by sinaowolabi** [comment]
Is this for beginners?

**Comment by amorriscode** [comment]
@sinaowolabi There are two other beginner classes, but depending on your experience this could be a good place to start.

**Comment by sinaowolabi** [comment]
Ok. Not so sure of myself...what are the other beginner classes, please?

**Comment by Nixerrr** [comment]
Hey @sinaowolabi, take a look here for the recommended intro courses: https://github.com/ossu/computer-science#introduction-to-computer-science

**Comment by waltervargas** [comment]
Hi Guys, I would like to join!

**Comment by belhassen07** [comment]
I've just started it , add me

**Comment by amorriscode** [comment]
@belhassen07 We are about to finish, you might want to create a new cohort.
