### ISSUE TITLE
[New Cohort] How to Code - Simple Data

### ISSUE THREAD

**Issue by Kun17** [ossu/cohorts#41]
## Class

Computer Science / Core Programming / How to Code - Simple Data

## Coordinators (1/3)

Kun

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- Add students here

## Start Date

Jan.08.2020

**Comment by ihaveapen** [comment]
Hey u still on board to start this?

**Comment by TheSovIndividual** [comment]
Hey guys,

seems we're lucky here - I'm also interested and currently at chapter 3b of the course.
Let's do this!

**Comment by Wetgou** [comment]
i'm interested

**Comment by TheSovIndividual** [comment]
I'm meanwhile in How to Code - Complex Data Chapter 10: Accumulators
Will continue with the Java Course afterwards. 
We can also chat on Gitter, there is more aktivity than here.

**Comment by Wetgou** [comment]
what's the gitter group?

**Comment by TheSovIndividual** [comment]
https://gitter.im/open-source-society/computer-science?utm_campaign=pr-badge&utm_content=badge&utm_medium=badge&utm_source=badge

**Comment by amorriscode** [comment]
How's the cohort going everyone? :)

**Comment by sidekicktal** [comment]
Hi, is anyone learning How to code- Simple Data, I am currently in 2: Data Definitions and will continue to How to code- Complex Data.

**Comment by waciumawanjohi** [comment]
- How to Code is estimated to take 2 months.
- The last student post was 6 months ago.
- There has been no response to amorriscode's check message.
- There is no link to a cohort specific discussion forum that might be more active (except for the main CS Gitter channel)

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should drop into the new Discord Server:
https://discord.gg/5pUhfpX
