### ISSUE TITLE
How to Code - Simple Data

### ISSUE THREAD

**Issue by OmarBobk** [ossu/cohorts#44]
## Class

Computer Science / Core Programming / How to Code - Simple Data

## Coordinators (1/3)

- Ahmad Omar

## Students (7/20)

- Ahmad Omar
- Anas Attar
- Hassan
- parthpatel227
- buoyantair
- zzzsoren
- lalumiere368 

## Start Date
Starts_at : 01/04/2020
Ends_at: 14/04/2020

# NOTE
If you are a beginner and feel that this period is short, you can double it, that is, do it twice, or divide the work into 3 hours per day instead of 6.

## Plan
_We have a plan that we have prepared, We will start this course on the first of next month (April) with an average of 6 hours per day and we will complete the course on the 14 of April_.

## Study times
01/04/2020 ----> 05/04/2020 : 5 days
06/04/2020 ----> HOLIDAY
07/04/2020 ----> 11/04/2020:  5 days
12/04/2020 ----> HOLIDAY
13/04/2020 ----> 14/04/2020: 2 days

## How to show your progress

1.  Create an account in [Trello](https://trello.com/).

2.  Copy [this](https://trello.com/b/7a5LEhv4) board to your personal account. See how to copy a board [here.](https://help.trello.com/article/802-copying-cards-lists-or-boards)

## Community
We will discuss our progress and problems in this room at gitter:
[https://gitter.im/ComputerScience2020/community](https://gitter.im/ComputerScience2020/community)

**Comment by amorriscode** [comment]
@A-omar-K you didn't put a start date for your cohort. Could you do that to allow other students some time to join?

**Comment by buoyantair** [comment]
Hi @A-omar-K ! Would love to join this cohort!

**Comment by shreyangoyal** [comment]
I'm interested.. Please share more details

**Comment by parthpatel227** [comment]
I am interested, please update the platform we will use to communicate.

**Comment by A-omar-K** [comment]
> Hi @A-omar-K ! Would love to join this cohort!

I will be happy with that. Review our plan and I will register you as **buoyantair** right ?

**Comment by parthpatel227** [comment]
@A-omar-K 
Add me too! Also it will be preferable if we create a communication channel if possible because it will help us get started and not wait around for 1st, as some of us may not be able to give 6 hours a day.

**Comment by shreyangoyal** [comment]
@A-omar-K please add me as well

**Comment by shreyangoyal** [comment]
> @A-omar-K please add me as well

Okay I misunderstood. I need to do the intro courses first on my own. Let me get done with those then will join the next cohort

**Comment by lalumiere368** [comment]
I am interested in joining as well. When does the next cohort start?

**Comment by OmarBobk** [comment]
@lalumiere368
> I am interested in joining as well. When does the next cohort start?

Hi lalumiere368 we will start on the first of April.

**Comment by zzzsoren** [comment]
I'd like to join if possible

**Comment by OmarBobk** [comment]
@zzzsoren 
> I'd like to join if possible

Of course you can I will add your name to the list

**Comment by OmarBobk** [comment]
Hello @amorriscode I've made edits to the cohort (like adding a new plan) several times and when I am done I click on the update button and everything is okay, but when I come back on the second day I don't see my new updates. do you think you can help me?

**Comment by amorriscode** [comment]
@OmarBobk let me know what you wish to edit and I can try! I'm not sure if there was a glitch in GitHub while you were trying to save. It looks like you made a successful edit two hours ago according to GitHub? 🤷‍♂

**Comment by OmarBobk** [comment]
@amorriscode Thank you for responding, 

> @OmarBobk let me know what you wish to edit and I can try! I'm not sure if there was a glitch in GitHub while you were trying to save. It looks like you made a successful edit two hours ago according to GitHub?

yes this edit that you are seeing is just the little one and I don't know why it is saved while the big edit that I made it twice disappeared. I will write it in comment so you can try.

**Comment by lalumiere368** [comment]
I can't get into the OSSU online app, which is where I assume a lot of this info is posted, it says there is a 410 error and an SDK update to firebase is required, which I don't think is something I would do on my end, please let me know if I'm wrong. It just doesn't let me log in with GitHub.

**Comment by amorriscode** [comment]
@lalumiere368 unfortunately the OSSU online app isn't maintained or used anymore.

**Comment by mc007-gh0st** [comment]
Hello all. I'd be interested in joining this cohort for how to code : simple data.

When is actual start date?

I'm totally new to OSSU and am having hard time taking courses alone.

Please anyone, point me in right direction. ..

Thanks....be blessed all....

**Comment by waciumawanjohi** [comment]
- How to Code is estimated to take 2 months.
- The last student post was 3 months ago.
- The last message in the cohort's Gitter channel was 4 months ago.

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should visit the new OSSU Discord server!
https://discord.gg/5pUhfpX
