### ISSUE TITLE
[New Cohort] Build a Modern Computer from First Principles: Nand to Tetris Part II

### ISSUE THREAD

**Issue by AR2030** [ossu/cohorts#46]
## Class

Computer Science / Core Systems / Build a Modern Computer from First Principles: Nand to Tetris Part II

## Coordinators (1/3)

- AR2030

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- AR2030

## Start Date
Starts_at : 01/05/2020
Ends_at: 1/06/2020

##plan 

We have a plan that we have prepared, We will start this course on the first of next month (May) with an average of 5 hours per day and we will complete the course on the 1 of June.

##Study times

-- to complete

**Comment by rodrigomlpOz** [comment]
I want to join! Have already complete Nand2Tetris part I =) What should I do next?

**Comment by pcolt** [comment]
Hello guys, I have started the course almost 1 week ago and I struggling with Project 8. 
So I really need help :-)

**Comment by pcolt** [comment]
Hey there, 
I am just finishing to watch all the videos form NandToTetris Part II and I found it quite demanding and time consuming to complete all the assignments. It is the hardest MOOC I have taken so far.
It would be great if we could join in a group and work on the assignments together, simulating some sort of developing team. What do you think?

**Comment by waciumawanjohi** [comment]
- The last student post was 4 months ago.
- There is no link to a cohort specific discussion forum that might be active.

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should visit the new OSSU Discord server!
https://discord.gg/5pUhfpX

There is a channel specifically for discussing Nand to Tetris Part II. https://discord.gg/AsUXcPu
