### ISSUE TITLE
[New Cohort] Introduction to Computer Science - CS50 

### ISSUE THREAD

**Issue by Millennial-Polymath** [ossu/cohorts#47]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science - CS50

## Students (1/20)

 Muchami Ngotho

## Start Date

7/04/2020 - 21/04/2020
 #startingsoon

**Comment by samanthanium** [comment]
Hi, I would like to join as a student!

**Comment by robbrit** [comment]
Hey folks, I'd be happy to help coordinate this one if you need help.

**Comment by aweasadbek** [comment]
Hello! I've just started this course, and it would be great to learn with new friends. I would like to join as a student!

**Comment by aweasadbek** [comment]
> Hey folks, I'd be happy to help coordinate this one if you need help.

It would be great!

**Comment by latinawhocodes** [comment]
I would like to join as a student! I've just started this course

**Comment by stefanokali** [comment]
Hi, I would like to join as a student. Just started this course.

**Comment by aweasadbek** [comment]
Join on discord, if you want to learn together! It would be great to all of us to communicate and learn together. https://discord.gg/rhVgAwq

**Comment by rodrigomlpOz** [comment]
I tutor this course professionally and would be more than happy to coordinate (for free, obviously) a cohort through Zoom meetings. If there is any interest email me at rodrigomlp@gmail.com, you guys can check out some of my content on my youtube channel https://www.youtube.com/channel/UCDe_yod9jfnAgbcRkyAFhpQ?view_as=subscriber

**Comment by aweasadbek** [comment]
Hi Rodrigo! We're chatting here https://discord.gg/rhVgAwq! You can joing if you can

**Comment by Menazaa** [comment]
I just started  this course, and I'd like to join as a student

**Comment by aweasadbek** [comment]
You are welcome to join to our community at Discord https://discord.gg/rhVgAwq!

**Comment by mauavilespi** [comment]
Hello! I would like to join as a student.

**Comment by jexchange** [comment]
Hey there! I'm new to the course and I would like to join as as well

**Comment by WalidBabi** [comment]
I just started this course, and I'd like to join as a student :)

**Comment by ahmadelzohairy** [comment]
Hi! I want to join to this cohort

**Comment by nguyenxuansang9494** [comment]
Hi! I want to join to this cohort as a student

**Comment by chaitanya710** [comment]
Hi
I would like to join this as a student

**Comment by robbrit** [comment]
Hey everyone, if you want to join then scroll up and click the Discord link. That's where you can ask questions and things.

**Comment by waciumawanjohi** [comment]
@Millennial-Polymath and @robbrit Is this cohort still active, or is this issue ready to be closed?

**Comment by Millennial-Polymath** [comment]
Hello, it is ready to be closed.

Kind regards,
Muchami Ngotho.
