### ISSUE TITLE
[New Cohort] Programming Languages, Part A B C

### ISSUE THREAD

**Issue by pcolt** [ossu/cohorts#48]
## Class

Computer Science / Core Programming / Programming Languages, Part A B C

## Coordinators (1/3)

- Rob
- Looking for coordinator(s)

## Students (3/20)

- Pablo @pcolt
- Alotaibit
- AbdesamedBendjeddou
- Looking for more students

## Start Date
Present session started on May 11th, 2020 at Coursera but feel free to join us later as well

## Join our Discord channel
Any other student or coordinator can join us here https://discord.gg/sK9vURC

**Comment by alotaibit** [comment]
Hi Pablo, 
I am interested to join the cohort.

**Comment by AbdesamedBendjeddou** [comment]
count me in

**Comment by robbrit** [comment]
I'd be happy to help coordinate.

**Comment by pcolt** [comment]
Wow, so happy to see you all on board! Thank you @robbrit for the help, I do really appreciate

**Comment by pcolt** [comment]
Hey guys,
The course looks like is started today so I have created a discord channel at [this link](https://discord.gg/sK9vURC) to meet all together. 
From my side I am going to need some additional day to finish the course Mathematics for CS that I started two weeks ago and I don't want to hang up, but I will show up here around in case.
Ah and I do not have previous experience with Discord so be patient asking for changes about the set up :)

**Comment by waciumawanjohi** [comment]
- The last student post was 3 months ago.
- The last message in the cohort's Discord channel was 1 month ago.

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should visit the new OSSU Discord server!
https://discord.gg/5pUhfpX
