### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by Omarabdul3ziz** [ossu/cohorts#49]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science and Programming using Python

## Coordinators (1/3)

- Waiting for a volunteer mentor

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- Omar Abdulaziz

## May 10, 2020

_Choose a start date for your cohort. We suggest providing two weeks for other students to join._

**Comment by maryam995** [comment]
I need to join how can I di that ?

**Comment by sh3ngsh3ng** [comment]
Hello! Interested!

**Comment by Taras-Protcyshyn** [comment]
Hi! I want to join to this cohort

**Comment by islamAwaad** [comment]
hi i want to join this cohort

**Comment by ahmadelzohairy** [comment]
hi how can i join this cohort

**Comment by ZineYT** [comment]
Hey I want to join!

**Comment by staycul** [comment]
Hey can I join this cohort? Thank you

**Comment by glendell03** [comment]
Hi I want to join :) Thank you

**Comment by LeahXia** [comment]
Is this for the upcoming one on Jun 3, 2020? If yes, plz count me in

**Comment by ahmadelzohairy** [comment]
I hope that too, some student want want ocw version i don't know what is the difference between ocw and edx versions.

**Comment by glendell03** [comment]
Hello u can join to my discord https://discord.gg/vCvszh

**Comment by vicverl** [comment]
Hi! I want to join this team!

**Comment by waciumawanjohi** [comment]
There have been no new messages in 2 months and the only link to a different discussion space is an expired Discord link. For this reason I'm closing this issue. Students looking to connect are welcome to join the official OSSU Discord server.

https://discord.gg/5pUhfpX
