### ISSUE TITLE
[New Cohort] Build a Modern Computer from First Principles: From Nand to Tetris

### ISSUE THREAD

**Issue by netship02** [ossu/cohorts#5]
## Class

Computer Science / Core Systems / Build a Modern Computer from First Principles: From Nand to Tetris

## Coordinators (1/3)

- [Deepak Singh Kushwaha](https://github.com/netship02)

## Students (3/20)

- [Deepak Singh Kushwaha](https://github.com/netship02)
- [Shaila Lias](https://github.com/shailalias)
- [Adam Clarkson](https://github.com/atclarkson)

## Start Date

December 18, 2017

[Join the Slack group](http://ossuniversity.slack.com) here, we have a channel called #nand2tetris

**Comment by shailalias** [comment]
I can join as a student. 
- Shaila Lias

**Comment by shailalias** [comment]
Since we are starting tomorrow, how do we plan to communicate?

**Comment by amorriscode** [comment]
@shailalias The class size is small so I think it'd be better to extend the start date to give other students a chance to jump on. However, you and @netship02 are more than welcome to start without other students of course.

In terms of communication, I recommend joining the [OSSU Slack group](https://join.slack.com/t/ossuniversity/shared_invite/enQtMjc1Njk0MDk5NDc4LWM1OTkwNjg5YmMxZWVlNzJjMTRmYTU0NjhiNDZmZTE0MjgzOTdiZjZlYmQ0MzI5ZTBkZDI4N2YwMDk5NDM1MmI)! You could make your own channel for this cohort!

**Comment by shailalias** [comment]
I'm fine with waiting. I was just wondering, since there hadn't been any updates recently.

**Comment by amorriscode** [comment]
Good luck! This course looks like a lot of fun, can't wait to get to it myself.

**Comment by netship02** [comment]
You may start if you have spare time. I have created a separate channel on slack for discussion.

**Comment by atclarkson** [comment]
I'll be joining you guys if that's all right!

**Comment by amorriscode** [comment]
@netship02 How's the cohort going? Let me know when the cohort is finished and who graduates so I can make a repo and close this issue.

**Comment by netship02** [comment]
I already have finished but last Week have programming(high level preq). So i am taking MIT python(currently at WEEK 6). In few days i will finish last week problem set. Please wait for some time.
@shailalias @atclarkson  @amorriscode

**Comment by netship02** [comment]
@amorriscode I have completed Final project. You may close this issue. 
Seems like other two guys drop this course. Anyway this was very interesting course.

**Comment by mvj3** [comment]
@netship02 @amorriscode I'm working on 4th week currently, could do you guys invite me to slack channel #nand2tetris ?
