### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by glendell03** [ossu/cohorts#51]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science and Programming using Python

## Coordinators (1/3)

1. Ranjit Singh

## Students (6/20)

1. Glendell
2. ahmadelzohairy
3. DigitalPromiseVictor
4. Hasssan-Ramadan
5. suryansh13-study
6. fromjdobson

## Start Date

**June 4, 2020**
[https://www.edx.org/course/introduction-to-computer-science-and-programming-7](url)
**Alternative**
[https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/](url)

Discord: https://discord.gg/X3jMxT

**Comment by ahmadelzohairy** [comment]
hi can i join

**Comment by DigitalPromiseVictor** [comment]
@glendell03 Discord link invalid. I'd be down to join as student.  What would coordination entail? Do ya'll wanna just set goal dates for each section and have regular check-ins?

**Comment by glendell03** [comment]
> @glendell03 Discord link invalid. I'd be down to join as student. What would coordination entail? Do ya'll wanna just set goal dates for each section and have regular check-ins?

https://discord.gg/9p8zuR

**Comment by glendell03** [comment]
Don't have any goals yet the course start at jun 3 will talk about how it goes when it's open

**Comment by Hasssan-Ramadan** [comment]
I Wanna join, plz.

**Comment by Hasssan-Ramadan** [comment]
> > @glendell03 Discord link invalid. I'd be down to join as student. What would coordination entail? Do ya'll wanna just set goal dates for each section and have regular check-ins?
> 
> https://discord.gg/9p8zuR

It still invalid, man!

**Comment by glendell03** [comment]
> > > @glendell03 Discord link invalid. I'd be down to join as student. What would coordination entail? Do ya'll wanna just set goal dates for each section and have regular check-ins?
> > 
> > 
> > https://discord.gg/9p8zuR
> 
> It still invalid, man!

https://discord.gg/X3jMxT

**Comment by 1nsp1r3rnzt** [comment]
I am willing to join as a coordinator.

**Comment by suryansh13-study** [comment]
I WANT TO JOIN AS STUDENT
LETS GOOOOOOOO

**Comment by glendell03** [comment]
> I am willing to join as a coordinator.

Hello yaay thank you :) here is the updated link of discord https://discord.gg/X3jMxT

> I WANT TO JOIN AS STUDENT
> LETS GOOOOOOOO

Hi click the link above to join :)

**Comment by fromjdobson** [comment]
I'd like to join as a student

**Comment by glendell03** [comment]
> I'd like to join as a student

Hi https://discord.gg/QxQDdN here the link

**Comment by Alqupaty** [comment]
Halllo guys
I would like to join as a student

**Comment by glendell03** [comment]
> Halllo guys
> I would like to join as a student

https://discord.gg/fXmX6A

**Comment by daaimah123** [comment]
Can I join this cohort?

**Comment by msnyarie** [comment]
hello guys can i plz join

**Comment by glendell03** [comment]
> hello guys can i plz join

https://discord.gg/2zJajd
you can join here :)

**Comment by thelastdB** [comment]
Hey all! I am also taking this course right now. Could I join the cohort?

**Comment by glendell03** [comment]
> Hey all! I am also taking this course right now. Could I join the cohort?

https://discord.gg/BrYGVE

**Comment by kedicode** [comment]
I am currently taking this course. May I please have an invite as well.

**Comment by glendell03** [comment]
> I am currently taking this course. May I please have an invite as well.

http://localhost:3000/signin

**Comment by kedicode** [comment]
> > I am currently taking this course. May I please have an invite as well.
> 
> http://localhost:3000/signin

localhost won't help me as that loops back to my machine. May I have a link please.

**Comment by 1nsp1r3rnzt** [comment]
> > > I am currently taking this course. May I please have an invite as well.
> > 
> > 
> > http://localhost:3000/signin
> 
> localhost won't help me as that loops back to my machine. May I have a link please.

The group is at https://discord.gg/MMAZ9n

**Comment by silas4869** [comment]
hi im a student i would also love to join!

**Comment by waciumawanjohi** [comment]
This thread has some half dozen invalid Discord invites. There is also what appears to be a joke, directing students to try to join by going to localhost.

I'm closing this.
