### ISSUE TITLE
[New Cohort] Build a Modern Computer from First Principles: From Nand to Tetris | & ||

### ISSUE THREAD

**Issue by Hasssan-Ramadan** [ossu/cohorts#53]
## Class

Computer Science / Core Systems / Build a Modern Computer from First Principles: From Nand to Tetris | & ||

## Coordinators (0/3)
>_looking for coordinators_

## Students (2/20)
- @Hasssan-Ramadan
- @1nsp1r3rnzt

## Start Date
**June 15, 2020**

## Links
Course Link: [Part |](https://www.coursera.org/learn/build-a-computer)  [Part ||](https://www.coursera.org/learn/nand2tetris2)
Alt Link: https://www.nand2tetris.org/
**Discord Link**: https://discord.gg/PCkrfVS

**Comment by 1nsp1r3rnzt** [comment]
Interested. Can you update the discord invite?

**Comment by Hasssan-Ramadan** [comment]
@1nsp1r3rnzt 
As a student or coordinator?
Discord invite already updated; It will not expired again.
Thanks for notifying me.
