### ISSUE TITLE
[New Cohort] Introduction to Interactive programming in python part 1 at Rice University 

### ISSUE THREAD

**Issue by Alqupaty** [ossu/cohorts#54]
## Class

Computer Science / Introduction To programming / Fundamentals of Computing Specialization / Introduction To Interactive programming  in python part 1

## Coordinators (1/3)
Looking after for Coordinators 

## Students (0/20)
1- Alqupaty
2- Alyameldir
3-centynla 

## Start Date
June 15, 2020
 

## Links
Course link :1st_place_medal: 
https://www.coursera.org/learn/interactive-python-1
Discard link :1st_place_medal: 
https://discord.gg/bsJFrJ

**Comment by silas4869** [comment]
hi guys i just started the ossu curriculum with "introduction to interactive programming (part 1) with python".

Is this cohort active?

(Is it rather too late for me to join? XD)

**Comment by waciumawanjohi** [comment]
- The Discord link in the cohort description is no longer active.
- A student asking for information about the cohort has gone unanswered for over a week.

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should visit the new OSSU Discord server!
https://discord.gg/5pUhfpX
