### ISSUE TITLE
Essence of Linear Algebra

### ISSUE THREAD

**Issue by jame78789** [ossu/cohorts#55]

**Comment by jame78789** [comment]
I always want to build a solid foundation on math, but some concept in the course is a little too arcane to me. So I hope someone good at math or you are just like me to discuss together.

**Comment by ahmadelzohairy** [comment]
I am same as you so I am taking https://www.edx.org/xseries/adelaidex-math-trackx in free time because i'm studying math alone,
I am currently in the second course. i'm TAKING THESE TO PREPARE for ossu calcus and linear algebra

**Comment by ahmadelzohairy** [comment]
I suggest you create discord room and start whatevet you comfortable with

**Comment by jame78789** [comment]
> I suggest you create discord room and start whatevet you comfortable with

Nice! I suggest you enroll with my cohort: https://github.com/ossu/cohorts/issues/56 to learn together. And my discord room is: https://discord.gg/rhvTWT you can visit if you want.

**Comment by waciumawanjohi** [comment]
- Essence of Linear Algebra should take no more than 2 weeks to watch.
- The last student post was 2 months ago.
- The Discord link is now invalid.

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should visit the new OSSU Discord server!
https://discord.gg/5pUhfpX
