### ISSUE TITLE
[New Cohort] Linear Algebra - Foundations to Frontiers

### ISSUE THREAD

**Issue by jame78789** [ossu/cohorts#56]
## Class

Computer Science / Core Math / Linear Algebra - Foundations to Frontiers

## Coordinators (1/3)

- Jame78789

## Students (0/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- None so far.

## Start Date

The cohort starts at Jul.1

**Comment by jame78789** [comment]
Really hoping someone good at math or just like me want to build a solid foundation on math to join!

**Comment by insaaniManav** [comment]
Hey how do i join ?

**Comment by waciumawanjohi** [comment]
- The last student post was 2 months ago.
- This student request received no answer.
- There is no link to a cohort discussion space.

From this I assume that the cohort has finished and I'm closing the issue. Students looking to connect with other OSSU learners should visit the new OSSU Discord server!
https://discord.gg/5pUhfpX
