### ISSUE TITLE
[New Cohort] Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by Pieter78** [ossu/cohorts#7]
## Class

Computer Science / Introduction To Computer Science / Introduction to Computer Science and Programming using Python

## Coordinators (1/3)

- Pieter Overbeek

## Students (3/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- Deepak Singh Kushwaha (netship02)
- chinmayshetye
- T-Seeker 

## Start Date

Monday, 22th January 2018

**Comment by Pieter78** [comment]
A new year has started, so let's get working on those New Year's Resolutions!

**Comment by Pieter78** [comment]
To get started I created a channel on the OSSU slack (ossuniversity.slack.com), the channel name is #python-002, join the channel if you're interested in joining the cohort!

**Comment by netship02** [comment]
Add as student Deepak Singh Kushwaha

**Comment by Pieter78** [comment]
Added! I'll extend the start date with a week to see if we can get a few more people involved.

**Comment by chinmayshetye** [comment]
I ll like to join.I am currently on lec2

**Comment by Pieter78** [comment]
Added both of you! If you like, see if you can hit us up on slack, ossuniversity.slack.com. The channel is named #python-002. We can make a plan there together and see how we want to move forward. Looking forward to it!

**Comment by callfactory** [comment]
Let's get this started! If you haven't make sure to join our slack channel (ossuniversity.slack.com), the channel name is #python-002.

I made a small provisional planning. It's self study so it's up to yourself how you actually want to approach it.

I'm planning to check in on the slack channel for weekly updates.

Good luck!

<img width="1064" alt="screen shot 2018-01-29 at 4 56 09 pm" src="https://user-images.githubusercontent.com/24841820/35516921-b7536086-0515-11e8-91cc-d78329330170.png">

**Comment by souperM** [comment]
Do you have an invite link to the slack group? I can't seem to find one anywhere.
Could I also be added to the cohort. I have already started this course but only just found out about the cohort system. Many thanks

**Comment by AnaRobynn** [comment]
What's the use-case spreading the community out into Gitter + Slack?

**Comment by amorriscode** [comment]
@AnaRobynn Slack is a little more feature rich and I like the way it handles rooms inside of an organization. It's what I use day to day at work so it was natural to me (I never use Gitter). I think the students can decide what they want, for now it's pretty impossible to force them to choose.

**Comment by amorriscode** [comment]
@Pieter78 How goes the studies? Should we close this up?
