### ISSUE TITLE
[New Cohort] Programming Languages, Part A

### ISSUE THREAD

**Issue by HassenPy** [ossu/cohorts#8]
## Class

[Computer Science / Core Programming / Programming Languages, Part A](https://www.coursera.org/learn/programming-languages)

## Coordinators (1/3)
- [Hassen ben tanfous](https://github.com/HassenPy)

## Students (4/8)
- [Mikhail Kirillov](https://github.com/w96k)
- [Miloky](https://github.com/Miloky)
- [Abdulah Hamzic](https://github.com/hamzicabdulah)
## Start Date
- January 22, 2018

Jump in to the [gitter room for this cohort](https://gitter.im/ossu-cohort-programming-languages-part-a/Lobby) and say hi.

**Comment by hamzicabdulah** [comment]
Abdulah Hamzic :)

**Comment by hamzicabdulah** [comment]
Have you guys started this one yet? I don't see a channel for this course in the OSSU Slack group.

**Comment by HassenPy** [comment]
oh, we have a gitter room for this, i went with it since most ossu people use it.

**Comment by HassenPy** [comment]
apologize for everyone who signed up on this, i got pressing events that prevented me from managing this, really sorry.
