### ISSUE TITLE
[New Cohort] How to Code - Complex Data

### ISSUE THREAD

**Issue by Nixerrr** [ossu/cohorts#9]
## Class

[Computer Science / Core Programming / How to Code - Complex Data](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x)

## Coordinators (2/3)

- [Anthony Morris](https://github.com/amorriscode)
- [Nikos Panaiotu](https://github.com/Nixerrr)

## Students (7/20)

- [Anthony Morris](https://github.com/amorriscode)
- [Nikos Panaiotu](https://github.com/Nixerrr)
- [Abdulah Hamzic](https://github.com/hamzicabdulah)
- [Vivek Poddar](https://github.com/vivekimsit)
- [Florian Hoornaar](https://github.com/FlorianHoornaar)
- [Deepak Kushwaha](https://github.com/netship02)
- [David Caron](https://github.com/davidcaron)

## Start Date

February 5, 2018

## Slack Channel

Join the [OSSU Slack workspace](https://join.slack.com/t/ossuniversity/shared_invite/enQtMjk4NDA5NDAzMzkyLTkwMDQ3MGVjNzYxMDg2ZmIwMmYwZjQ0ZDI1OTdmODdlNDNkZTdlOTZjMWJlMmNhMTZiZjlkNWIzNDliMjEzZTI), then find the channel #howtocode-cd-002

**Comment by amorriscode** [comment]
Thanks for signing me up! Can't wait to get started on this. 💯

**Comment by hamzicabdulah** [comment]
Abdulah Hamzic

**Comment by vivekimsit** [comment]
Vivek Poddar

**Comment by FlorianHoornaar** [comment]
Florian Hoornaar

**Comment by netship02** [comment]
Deepak Kushwaha

**Comment by Nixerrr** [comment]
The Slack channel is #howtocode-cd-002.

**Comment by davidcaron** [comment]
David Caron
